version: '3.3'
services:
  wiam-postgres:
    image: postgres:15-alpine
    networks:
      - wiam
    volumes:
      - wiam-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: wiam
      POSTGRES_USER: wiam
      POSTGRES_PASSWORD: wiam
    ports:
      - "5433:5432"
    restart: always
  wiam-nginx:
    image: nginx:alpine
    working_dir: /application
    networks:
      - wiam
    volumes:
      - .:/application
      - ./environment-config/dev/nginx/default.local.nginx:/etc/nginx/conf.d/default.conf
    depends_on:
      - wiam-app
    ports:
      - "8000:80"
  wiam-app:
    build:
      context: .
      dockerfile: DockerfileDev
    user: ${UID}:${GUID}
    env_file:
      - .env
    networks:
      - wiam
    depends_on:
      - wiam-postgres
    restart: always
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - .:/application
      - ./environment-config/dev/php/php-ini-overrides.local.ini:/usr/local/etc/php/conf.d/php.ini
volumes:
  wiam-postgres:

networks:
  wiam: