version: '3.3'
services:
  wiam-prod-postgres:
    image: postgres:15-alpine
    networks:
      - wiam-prod
    volumes:
      - wiam-prod-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: wiam-prod
      POSTGRES_USER: wiam-prod
      POSTGRES_PASSWORD: wiam-prod
    ports:
      - "5434:5432"
    restart: always
  wiam-prod-nginx:
    build:
      context: .
      dockerfile: DockerfileNginx
    networks:
      - wiam-prod
    volumes:
      - wiam-prod-app:/application
    depends_on:
      - wiam-prod-app
    ports:
      - "8800:80"
    restart: always
  wiam-prod-app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env-prod
    networks:
      - wiam-prod
    volumes:
      - wiam-prod-app:/application
    depends_on:
      - wiam-prod-postgres
    restart: always
volumes:
  wiam-prod-postgres:
  wiam-prod-app:

networks:
  wiam-prod: